[package]
name = "splat"
version = "1.1.0"
authors = ["Matthias Vogelgesang"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
image = { version = "0", default-features = false, features = ["jpeg", "png", "webp", "rayon"] }
pulldown-cmark = "0"
rayon = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
tera = "1"
toml = "1"

[dev-dependencies]
tempfile = "3"

[lints.clippy]
unwrap_used = "deny"

[profile.release]
codegen-units = 1
lto = true
