[package]
name = "splat"
version = "0.1.0"
authors = ["Matthias Vogelgesang"]
edition = "2018"

[dependencies]
anyhow = "1"
image = "0"
regex = "1"
serde = "1"
serde_derive = "1"
structopt = { version = "0", default-features = false }
tera = "1"
toml = "0"

[dev-dependencies]
tempfile = "3"
